version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    versioning-strategy: increase
    reviewers:
      - "Lucas-Angelo"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "devops"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/Codigo/jobscheduler-service"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    versioning-strategy: increase
    reviewers:
      - "Lucas-Angelo"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "backend"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/Codigo/supportplatform-service"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    versioning-strategy: increase
    reviewers:
      - "Lucas-Angelo"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "backend"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/Codigo/supportplatform-web"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    versioning-strategy: increase
    reviewers:
      - "guizombas"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "frontend"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/Codigo/jobscheduler-service"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    versioning-strategy: increase
    reviewers:
      - "Lucas-Angelo"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "devops"
      - "backend"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/Codigo/supportplatform-service"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    versioning-strategy: increase
    reviewers:
      - "Lucas-Angelo"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "devops"
      - "backend"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/Codigo/supportplatform-web"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    versioning-strategy: increase
    reviewers:
      - "Lucas-Angelo"
      - "guizombas"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "devops"
      - "frontend"
