version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    reviewers:
      - "ICEI-PUC-Minas-PPLES-TI/plataformaapoioavaliacoesprojetos"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "devops"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/Codigo/jobscheduler-service"
    schedule:
      interval: "daily"
    reviewers:
      - "ICEI-PUC-Minas-PPLES-TI/plataformaapoioavaliacoesprojetos"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "backend"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/Codigo/supportplatform-service"
    schedule:
      interval: "daily"
    reviewers:
      - "ICEI-PUC-Minas-PPLES-TI/plataformaapoioavaliacoesprojetos"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "backend"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/Codigo/supportplatform-web"
    schedule:
      interval: "daily"
    reviewers:
      - "ICEI-PUC-Minas-PPLES-TI/plataformaapoioavaliacoesprojetos"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "frontend"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/Codigo/jobscheduler-service"
    schedule:
      interval: "daily"
    reviewers:
      - "ICEI-PUC-Minas-PPLES-TI/plataformaapoioavaliacoesprojetos"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "devops"
      - "backend"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/Codigo/supportplatform-service"
    schedule:
      interval: "daily"
    reviewers:
      - "ICEI-PUC-Minas-PPLES-TI/plataformaapoioavaliacoesprojetos"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "devops"
      - "backend"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/Codigo/supportplatform-web"
    schedule:
      interval: "daily"
    reviewers:
      - "ICEI-PUC-Minas-PPLES-TI/plataformaapoioavaliacoesprojetos"
    labels:
      - "auto"
      - "dependency"
      - "technical debt"
      - "devops"
      - "frontend"
