import { repositoryTestingSeed } from "./repository";

const branchTestingSeed = [
    {
        id: 1,
        name: "main",
        repositoryId: repositoryTestingSeed[0].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 2,
        name: "dev",
        repositoryId: repositoryTestingSeed[0].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 3,
        name: "main",
        repositoryId: repositoryTestingSeed[1].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 4,
        name: "master",
        repositoryId: repositoryTestingSeed[1].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 5,
        name: "main",
        repositoryId: repositoryTestingSeed[2].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 6,
        name: "branch1",
        repositoryId: repositoryTestingSeed[2].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 7,
        name: "branch2",
        repositoryId: repositoryTestingSeed[2].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 8,
        name: "branch3",
        repositoryId: repositoryTestingSeed[2].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 9,
        name: "branch4",
        repositoryId: repositoryTestingSeed[2].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 10,
        name: "branch5",
        repositoryId: repositoryTestingSeed[2].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 11,
        name: "branch6",
        repositoryId: repositoryTestingSeed[2].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 12,
        name: "branch7",
        repositoryId: repositoryTestingSeed[2].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 13,
        name: "branch8",
        repositoryId: repositoryTestingSeed[2].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 14,
        name: "branch9",
        repositoryId: repositoryTestingSeed[2].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 15,
        name: "branch10",
        repositoryId: repositoryTestingSeed[2].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 16,
        name: "branch11",
        repositoryId: repositoryTestingSeed[2].id,
        commitAutomaticSynchronization: false,
        fileAutomaticSynchronization: false,
    },
    {
        id: 17,
        name: "main",
        repositoryId: repositoryTestingSeed[3].id,
        commitAutomaticSynchronization: true,
        fileAutomaticSynchronization: true,
    },
];

export { branchTestingSeed };
