const contributorTestingSeed = [
    {
        id: 1,
        githubId: "githubId1",
        githubEmail: "johnd@email.com",
        githubLogin: "johnd",
        githubName: "John Doe",
        githubAvatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
    },
    {
        id: 2,
        githubId: "githubId2",
        githubEmail: null,
        githubLogin: "janed",
        githubName: null,
        githubAvatarUrl: null,
    },
    {
        id: 3,
        githubId: "githubId3",
        githubEmail: "august@email.com.br",
        githubLogin: "august",
        githubName: "August",
        githubAvatarUrl: "https://avatars.githubusercontent.com/u/3?v=4",
    },
    {
        id: 4,
        githubId: "githubId4",
        githubEmail: null,
        githubLogin: "cjgtasa",
        githubName: "Carl Jonhson",
        githubAvatarUrl: null,
    },
    {
        id: 5,
        githubId: "githubId5",
        githubEmail: null,
        githubLogin: "iamauser",
        githubName: "github User",
        githubAvatarUrl: null,
    },
    {
        id: 6,
        githubId: "githubId6",
        githubEmail: null,
        githubLogin: "iamauser2",
        githubName: "github User 2",
        githubAvatarUrl: null,
    },
    {
        id: 7,
        githubId: "githubId7",
        githubEmail: null,
        githubLogin: "iamauser3",
        githubName: "github User 3",
        githubAvatarUrl: null,
    },
    {
        id: 8,
        githubId: "githubId8",
        githubEmail: null,
        githubLogin: "iamauser4",
        githubName: "github User 4",
        githubAvatarUrl: null,
    },
    {
        id: 9,
        githubId: "githubId9",
        githubEmail: null,
        githubLogin: "iamauser5",
        githubName: "github User 5",
        githubAvatarUrl: null,
    },
    {
        id: 10,
        githubId: "githubId10",
        githubEmail: null,
        githubLogin: "iamauser6",
        githubName: "github User 6",
        githubAvatarUrl: null,
    },
    {
        id: 11,
        githubId: "githubId11",
        githubEmail: null,
        githubLogin: "iamauser7",
        githubName: "github User 7",
        githubAvatarUrl: null,
    },
    {
        id: 12,
        githubId: "githubId12",
        githubEmail: null,
        githubLogin: "iamauser8",
        githubName: "github User 8",
        githubAvatarUrl: null,
    },
];

export { contributorTestingSeed };
