import { IEvaluationMethodAttributes } from "../../model/EvaluationMethod";

const evaluationMethodTestingSeed: IEvaluationMethodAttributes[] = [
    {
        id: 1,
        description: "Interdisciplinary Work 1",
        semester: 1,
        year: 2021,
        disabledAt: new Date("2023-09-10"),
    },
    {
        id: 2,
        description: "Interdisciplinary Work 2",
        semester: 1,
        year: 2021,
        disabledAt: new Date("2023-09-10"),
    },
    {
        id: 3,
        description: "Interdisciplinary Work 3",
        semester: 1,
        year: 2021,
        disabledAt: new Date("2023-09-10"),
    },
    {
        id: 4,
        description: "Interdisciplinary Work 4",
        semester: 1,
        year: 2021,
        disabledAt: new Date("2023-09-10"),
    },
    {
        id: 5,
        description: "Interdisciplinary Work 5",
        semester: 1,
        year: 2021,
        disabledAt: new Date("2023-09-10"),
    },
    {
        id: 6,
        description: "Interdisciplinary Work 6",
        semester: 1,
        year: 2021,
        disabledAt: new Date("2023-09-10"),
    },
    {
        id: 7,
        description: "Interdisciplinary Work 1",
        semester: 2,
        year: 2021,
        disabledAt: new Date("2023-09-10"),
    },
    {
        id: 8,
        description: "Interdisciplinary Work 2",
        semester: 2,
        year: 2021,
        disabledAt: new Date("2023-09-10"),
    },
    {
        id: 9,
        description: "Interdisciplinary Work 3",
        semester: 2,
        year: 2021,
        disabledAt: new Date("2023-09-10"),
    },
    {
        id: 10,
        description: "Interdisciplinary Work 4",
        semester: 2,
        year: 2021,
        disabledAt: new Date("2023-09-10"),
    },
    {
        id: 11,
        description: "Interdisciplinary Work 5",
        semester: 2,
        year: 2021,
        disabledAt: new Date("2023-09-10"),
    },
    {
        id: 12,
        description: "Interdisciplinary Work 6",
        semester: 2,
        year: 2021,
        disabledAt: new Date("2023-09-10"),
    },
    {
        id: 13,
        description: "Interdisciplinary Work 1",
        semester: 1,
        year: 2022,
        disabledAt: null,
    },
    {
        id: 14,
        description: "Interdisciplinary Work 2",
        semester: 1,
        year: 2022,
        disabledAt: null,
    },
    {
        id: 15,
        description: "Interdisciplinary Work 3",
        semester: 1,
        year: 2022,
        disabledAt: null,
    },
    {
        id: 16,
        description: "Interdisciplinary Work 4",
        semester: 1,
        year: 2022,
        disabledAt: null,
    },
    {
        id: 17,
        description: "Interdisciplinary Work 5",
        semester: 1,
        year: 2022,
        disabledAt: null,
    },
    {
        id: 18,
        description: "Interdisciplinary Work 6",
        semester: 1,
        year: 2022,
        disabledAt: null,
    },
    {
        id: 19,
        description: "Interdisciplinary Work 1",
        semester: 2,
        year: 2022,
        disabledAt: null,
    },
    {
        id: 20,
        description: "Interdisciplinary Work 2",
        semester: 2,
        year: 2022,
        disabledAt: null,
    },
    {
        id: 21,
        description: "Interdisciplinary Work 3",
        semester: 2,
        year: 2022,
        disabledAt: null,
    },
    {
        id: 22,
        description: "Interdisciplinary Work 4",
        semester: 2,
        year: 2022,
        disabledAt: null,
    },
    {
        id: 23,
        description: "Interdisciplinary Work 5",
        semester: 2,
        year: 2022,
        disabledAt: null,
    },
    {
        id: 24,
        description: "Interdisciplinary Work 6",
        semester: 2,
        year: 2022,
        disabledAt: null,
    },
    {
        id: 25,
        description: "Interdisciplinary Work 1",
        semester: 1,
        year: 2023,
        disabledAt: null,
    },
    {
        id: 26,
        description: "Interdisciplinary Work 2",
        semester: 1,
        year: 2023,
        disabledAt: null,
    },
    {
        id: 27,
        description: "Interdisciplinary Work 3",
        semester: 1,
        year: 2023,
        disabledAt: null,
    },
    {
        id: 28,
        description: "Interdisciplinary Work 4",
        semester: 1,
        year: 2023,
        disabledAt: null,
    },
    {
        id: 29,
        description: "Interdisciplinary Work 5",
        semester: 1,
        year: 2023,
        disabledAt: null,
    },
    {
        id: 30,
        description: "Interdisciplinary Work 6",
        semester: 1,
        year: 2023,
        disabledAt: null,
    },
    {
        id: 31,
        description: "Interdisciplinary Work 1",
        semester: 2,
        year: 2023,
        disabledAt: null,
    },
    {
        id: 32,
        description: "Interdisciplinary Work 2",
        semester: 2,
        year: 2023,
        disabledAt: null,
    },
    {
        id: 33,
        description: "Interdisciplinary Work 3",
        semester: 2,
        year: 2023,
        disabledAt: null,
    },
    {
        id: 34,
        description: "Interdisciplinary Work 4",
        semester: 2,
        year: 2023,
        disabledAt: null,
    },
    {
        id: 35,
        description: "Interdisciplinary Work 5",
        semester: 2,
        year: 2023,
        disabledAt: null,
    },
    {
        id: 36,
        description: "Interdisciplinary Work 6",
        semester: 2,
        year: 2023,
        disabledAt: null,
    },
];

export { evaluationMethodTestingSeed };
