import { IRepositoryAttributes } from "../../model/Repository";

const repositoryTestingSeed: IRepositoryAttributes[] = [
    {
        id: 1,
        githubId: "repo1",
        name: "typescript-utilsTxT",
        description: "Collection of utility functions for TypeScript",
        stargazerCount: 100,
        forkCount: 25,
        githubCreatedAt: new Date("2022-01-10"),
        githubUpdatedAt: new Date("2023-08-15"),
        hasProjectsEnabled: true,
        hasIssuesEnabled: true,
        primaryLanguage: "TypeScript",
        licenseName: "MIT",
        defaultBranch: "main",
        automaticSynchronization: true,
        synchronizing: false,
        lastSyncAt: null,
    },
    {
        id: 2,
        githubId: "repo2",
        name: "reactive-dashboard",
        description: "Interactive dashboard built with React and D3",
        stargazerCount: 75,
        forkCount: 15,
        githubCreatedAt: new Date("2021-03-20"),
        githubUpdatedAt: new Date("2023-08-18"),
        hasProjectsEnabled: true,
        hasIssuesEnabled: true,
        primaryLanguage: "JavaScript",
        licenseName: "MIT",
        defaultBranch: "master",
        automaticSynchronization: false,
        synchronizing: false,
        lastSyncAt: null,
    },
    {
        id: 3,
        githubId: "repo3",
        name: "python-data-tools",
        description: "Tools and libraries for working with data in Python",
        stargazerCount: 120,
        forkCount: 30,
        githubCreatedAt: new Date("2020-07-05"),
        githubUpdatedAt: new Date("2023-08-20"),
        hasProjectsEnabled: true,
        hasIssuesEnabled: true,
        primaryLanguage: "Python",
        licenseName: "Apache-2.0",
        defaultBranch: "main",
        automaticSynchronization: true,
        synchronizing: false,
        lastSyncAt: null,
    },
    {
        id: 4,
        githubId: "repo4",
        name: "vue-components-library",
        description: "Reusable components library for Vue.js",
        stargazerCount: 50,
        forkCount: 10,
        githubCreatedAt: new Date("2019-12-12"),
        githubUpdatedAt: new Date("2023-08-23"),
        hasProjectsEnabled: true,
        hasIssuesEnabled: true,
        primaryLanguage: "Vue.js",
        licenseName: "MIT",
        defaultBranch: "main",
        automaticSynchronization: true,
        synchronizing: false,
        lastSyncAt: null,
    },
    {
        id: 5,
        githubId: "repo5",
        name: "machine-learning-algos",
        description: "Implementation of various machine learning algorithms",
        stargazerCount: 200,
        forkCount: 50,
        githubCreatedAt: new Date("2018-06-25"),
        githubUpdatedAt: new Date("2023-08-20"),
        hasProjectsEnabled: true,
        hasIssuesEnabled: true,
        primaryLanguage: "Python",
        licenseName: "GNU GPL-3.0",
        defaultBranch: "dev",
        automaticSynchronization: true,
        synchronizing: false,
        lastSyncAt: null,
    },
    {
        id: 6,
        githubId: "repo6",
        name: "angular-starter-kit",
        description: "Starter kit for Angular applications with best practices",
        stargazerCount: 60,
        forkCount: 8,
        githubCreatedAt: new Date("2019-01-18"),
        githubUpdatedAt: new Date("2023-08-18"),
        hasProjectsEnabled: true,
        hasIssuesEnabled: true,
        primaryLanguage: "TypeScript",
        licenseName: "MIT",
        defaultBranch: "main",
        automaticSynchronization: false,
        synchronizing: false,
        lastSyncAt: null,
    },
    {
        id: 7,
        githubId: "repo7",
        name: "fullstack-node-react",
        description: "Full-stack application using Node.js and React",
        stargazerCount: 90,
        forkCount: 12,
        githubCreatedAt: new Date("2020-02-28"),
        githubUpdatedAt: new Date("2023-08-20"),
        hasProjectsEnabled: true,
        hasIssuesEnabled: true,
        primaryLanguage: "JavaScript",
        licenseName: "MIT",
        defaultBranch: "master",
        automaticSynchronization: true,
        synchronizing: false,
        lastSyncAt: null,
    },
    {
        id: 8,
        githubId: "repo8",
        name: "data-visualization-tools",
        description: "Tools for creating interactive data visualizations",
        stargazerCount: 110,
        forkCount: 20,
        githubCreatedAt: new Date("2018-09-15"),
        githubUpdatedAt: new Date("2023-08-22"),
        hasProjectsEnabled: true,
        hasIssuesEnabled: true,
        primaryLanguage: "JavaScript",
        licenseName: "MIT",
        defaultBranch: "main",
        automaticSynchronization: false,
        synchronizing: false,
        lastSyncAt: null,
    },
    {
        id: 9,
        githubId: "repo9",
        name: "rust-web-api",
        description: "Web API built with Rust programming language",
        stargazerCount: 40,
        forkCount: 6,
        githubCreatedAt: new Date("2021-06-10"),
        githubUpdatedAt: new Date("2023-08-18"),
        hasProjectsEnabled: true,
        hasIssuesEnabled: true,
        primaryLanguage: "Rust",
        licenseName: "MIT",
        defaultBranch: "main",
        automaticSynchronization: true,
        synchronizing: false,
        lastSyncAt: null,
    },
    {
        id: 10,
        githubId: "repo10",
        name: "express-mongodb-api",
        description: "RESTful API using Express.js and MongoDB",
        stargazerCount: 80,
        forkCount: 18,
        githubCreatedAt: new Date("2019-05-22"),
        githubUpdatedAt: new Date("2023-08-22"),
        hasProjectsEnabled: true,
        hasIssuesEnabled: true,
        primaryLanguage: "JavaScript",
        licenseName: "Apache-2.0",
        defaultBranch: "master",
        automaticSynchronization: true,
        synchronizing: false,
        lastSyncAt: null,
    },
    {
        id: 11,
        githubId: "repo11",
        name: "vue3-todo-app",
        description: "Simple todo app built with Vue 3",
        stargazerCount: 65,
        forkCount: 9,
        githubCreatedAt: new Date("2020-12-05"),
        githubUpdatedAt: new Date("2023-08-21"),
        hasProjectsEnabled: true,
        hasIssuesEnabled: true,
        primaryLanguage: "Vue.js",
        licenseName: "MIT",
        defaultBranch: "main",
        automaticSynchronization: true,
        synchronizing: false,
        lastSyncAt: null,
    },
    {
        id: 12,
        githubId: "repo12",
        name: "react-native-startertxt",
        description: "Starter template for building React Native applications",
        stargazerCount: 70,
        forkCount: 14,
        githubCreatedAt: new Date("2019-08-10"),
        githubUpdatedAt: new Date("2023-08-23"),
        hasProjectsEnabled: true,
        hasIssuesEnabled: true,
        primaryLanguage: "JavaScript",
        licenseName: "MIT",
        defaultBranch: "main",
        automaticSynchronization: true,
        synchronizing: false,
        lastSyncAt: null,
    },
];

export { repositoryTestingSeed };
