import express, { Express } from "express";
import applyErrorHandler from "./error/ErrorHandler";
import applyCorsMiddleware from "./middleware/CorsMiddleware";
import { applyGithubAuthMiddleware } from "./middleware/GithubAuthMiddleware";
import applySwaggerMiddleware from "./middleware/SwaggerMiddleware";
import { RegisterRoutes } from "./swagger/routes";

const app: Express = express();

applyCorsMiddleware(app); // Need be the first middleware because this allow requests
applyGithubAuthMiddleware(app); // Need be the second middleware because this will protect routes with authentication
applySwaggerMiddleware(app);
RegisterRoutes(app); // Register routes generated by tsoa

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

applyErrorHandler(app);

export default app;
