version: "3.9"

services:
  mysql_gitgrade:
    image: mysql:8.1.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_DOCKER_PORT
    expose:
      - $DB_PORT
    networks:
      - gitgrade-network
    volumes:
      - mysql_gitgrade_data:/var/lib/mysql
    env_file:
      - .env

  jobscheduler-service:
    build:
      context: ./jobscheduler-service/
      dockerfile: Dockerfile
    working_dir: /usr/src/gitgrade/jobscheduler_service/
    restart: unless-stopped
    depends_on:
      - mysql_gitgrade
    environment:
      - DB_HOST=mysql_gitgrade
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_DOCKER_PORT
      - JOBSCHEDULER_NODE_PORT=$JOBSCHEDULER_NODE_PORT
      - NODE_ENV=$NODE_ENV
      - APP_TIMEZONE=$APP_TIMEZONE
      - DB_DIALECT=$DB_DIALECT
      - DB_CHARSET=$DB_CHARSET
      - DB_COLLATE=$DB_COLLATE
      - DB_TIMEZONE=$DB_TIMEZONE
      - SYNC_TIME=$SYNC_TIME
      - APP_DEBUG=$APP_DEBUG
      - GITHUB_PERSONAL_ACCESS_TOKEN=$GITHUB_PERSONAL_ACCESS_TOKEN
      - GITHUB_ORGANIZATION_NAME=$GITHUB_ORGANIZATION_NAME
      - TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID
    command: /bin/bash -c "/usr/wait-for-it.sh --timeout=600 mysql_gitgrade:$DB_DOCKER_PORT && npm run start:dev"
    ports:
      - $JOBSCHEDULER_NODE_PORT:3000
    expose:
      - $JOBSCHEDULER_NODE_PORT
    networks:
      - gitgrade-network
    volumes:
      - jobscheduler_node_modules:/usr/src/gitgrade/jobscheduler_service/node_modules
    env_file:
      - .env

volumes:
  mysql_gitgrade_data:
    driver: local
  jobscheduler_node_modules:
    driver: local

networks:
  gitgrade-network:
    driver: bridge
