#!/usr/bin/env sh
#. "$(dirname -- "$0")/_/husky.sh"

# commit-message
echo "Validating commit message..."

if npx commitlint --edit $1 ; then
    echo "Commit message follows the pattern!" &&
    exec >/dev/tty 2>&1
else 
    # fix terminal bug
    exec >/dev/tty 2>&1 && 
    exit 1
fi