name: Auto PullRequest

on:
  push:
    branches:
      - "feature/*"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md" # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_label: "auto"
          pr_allow_empty: true
