name: Compress Images

on:
  pull_request:
    paths:
      - "Codigo/**.jpg"
      - "Codigo/**.jpeg"
      - "Codigo/**.png"
      - "Codigo/**.webp"

jobs:
  build:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ github.token }}
          ignorePaths: "Artefatos/**,Documentacao/**,Divulgacao/**"
