name: SupportPlatform Service Lint

on:
  workflow_call:
  pull_request:
    paths:
      - "Codigo/supportplatform-service/**"

jobs:
  lint:
    name: SupportPlatform Service Lint | OS ${{ matrix.os }} - Node Version ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          tool_name: eslint-github-pr-review
          workdir: ./Codigo/supportplatform-service
          reporter: github-pr-review
          level: error
          github_token: ${{ github.token }}
